Update es-ES.coffee
codecombat/codecombat pull request #6072
Opened 2020-12-06 11:17 UTC by Meagain13

title: "CodeCombat - Juegos de programación para aprender Python y JavaScript"
#    meta_keywords: "CodeCombat, python, javascript, juegos de programación"
#    meta_description: "Aprende a escribir código a través de un juego de programación. Aprende Python, JavaScript y HTML mientras resuelves rompecabezas y aprendes a hacer tus propios juegos de código y páginas web"
#    become_investor: "para convertirte en inversor en CodeCombat"
#    built_for_teachers_title: "Un juego de programación creado teniendo en cuenta a los maestros"
#    built_for_teachers_blurb: "Enseñar a los niños a programar puede ser abrumador. CodeCombat ayuda a todos los educadores a enseñar a los estudiantes cómo programar en JavaScript o Python, dos de los lenguajes de programación más populares. Con un exhaustivo plan de estudios que incluye seis unidades de Informática, y refuerza el aprendizaje a través de unidades en el desarrollo de juegos y desarrollo web basados en proyectos, los niños progresarán en un viaje ¡desde la sintaxis básica hasta la recursividad!"
#    built_for_teachers_subtitle1: "Informática"
#    built_for_teachers_subblurb1: "Empezando con nuestro curso gratuito de Introducción a la informática, los estudiantes dominarán los conceptos básicos de programación, como los bucles while / for, las funciones y los algoritmos"
#    built_for_teachers_subtitle2: "Desarrollo de juegos"
#    built_for_teachers_subblurb2: "Los alumnos construyen laberintos y utilizan el manejo de entrada básico para programar sus propios juegos que podrán compartir con amigos y familiares"
#    built_for_teachers_subtitle3: "Desarrollo Web"
#    built_for_teachers_subblurb3: "Usando HTML, CSS y jQuery, los estudiantes ejercitan su musculatura creativa para programar sus propias páginas web con una URL personalizada que podrán compartir con sus compañeros de clase"
    century_skills_title: "Habilidades del siglo XXI"
#    century_skills_blurb1: "NO solo el héroe de los estudiantes asciende de nivel, ELLOS mismos ascienden"
#    century_skills_quote1: "Te equivocas... luego piensas en todas las formas posibles de solucionarlo y luego lo intentas de nuevo. No podría llegar hasta aquí sin esforzarme"
#    century_skills_subtitle1: "Pensamiento crítico"
#    century_skills_subblurb1: "Con rompecabezas de programación organizándose naturalmente en niveles cada vez más desafiantes, el juego de programación de CodeCombat garantiza que los niños practiquen el pensamiento crítico continuamente"
#    century_skills_quote2: "Todos los demás estaban haciendo laberintos, así que pensé en 'capturar la bandera' y eso es lo que hice"
#    century_skills_subtitle2: "Creatividad"
#    century_skills_subblurb2: "CodeCombat anima a los estudiantes a mostrar su creatividad construyendo y compartiendo sus propios juegos y páginas web"
#    century_skills_quote3: "Si me atasco en un nivel, trabajo con la gente que me rodea hasta que entre todos podamos resolverlo"
#    century_skills_subtitle3: "Colaboración"
#    century_skills_subblurb3: "A lo largo del juego hay oportunidades para que los estudiantes colaboren cuando se atasquen y trabajen juntos utilizando nuestra guía de programación en pareja"
#    century_skills_quote4: "Siempre he tenido la aspiración de diseñar videojuegos y aprender a programar... y esto me está dando un gran punto de partida"
#    century_skills_subtitle4: "Comunicación"
#    century_skills_subblurb4: "La programación requiere que los niños practiquen nuevas formas de comunicación, incluidas la comunicación con la computadora y la transmisión de sus ideas a través del código más eficiente"
#    classroom_in_box_title: "Nos esforzamos por:"
#    classroom_in_box_blurb1: "Involucrar a todos los estudiantes para que confíen en que la programación es para ellos"
#    classroom_in_box_blurb2: "Darle a cualquier educador el poder para que se sienta seguro enseñando programación"
#    classroom_in_box_blurb3: "Inspirar a todos los líderes escolares para crear un programa de informática de clase mundial"
#    covid19_banner_blurb: "Ofrecemos acceso gratuito a nuestro plan de estudios completo a los educadores y escuelas afectadas por el cierre de colegios"
#    click_here: "Haz click aquí"
#    creativity_rigor_title: "Donde la creatividad alcanza el rigor"
#    creativity_rigor_subtitle1: "Haz que la programación sea divertida y enseñe habilidades del mundo real"
#    creativity_rigor_blurb1: "Los estudiantes escriben Python y JavaScript real mientras juegan a juegos que fomentan el ensayo-error, el pensamiento crítico y la creatividad. Y luego, aplican las habilidades de programación aprendidas al desarrollar sus propios juegos y sitios web en cursos basados en proyectos"
#    creativity_rigor_subtitle2: "Alcanza a los alumnos a sus niveles"
#    creativity_rigor_blurb2: "Cada nivel de CodeCombat está basado en millones de datos y optimizado para adaptarse a cada alumno. Los niveles de práctica y las pistas ayudan a los estudiantes cuando se atascan, y los niveles de desafío evalúan su aprendizaje a lo largo del juego"
#    creativity_rigor_subtitle3: "Creado para todos los maestros, independientemente de su experiencia"
#    creativity_rigor_blurb3: "El plan de estudios, a ritmo propio y alineado con los estándares, que ofrece CodeCombat, hace posible la enseñanza de la informática para todos. CodeCombat equipa a los maestros con formación, recursos de instrucción y apoyo dedicado para que se sientan seguros y exitosos en el aula"
#    featured_partners_title1: "Presentado en"
#    featured_partners_title2: "Premios y socios"
#    featured_partners_blurb1: "Socio Inteligente"
#    featured_partners_blurb2: "La mejor herramienta de creatividad para estudiantes"
#    featured_partners_blurb3: "La mejor elección para el aprendizaje"
#    featured_partners_blurb4: "Socio oficial de Code.org"

2020-12-14 16:49 UTC, nwinter requested changes
Looks great! We just need to uncomment each added translation so that it takes effect by deleting the leading `#` at the start of each line.

Also, so that we can merge this in, can you [sign the CLA](https://codecombat.com/cla)? (It's easy.)

2020-12-19 10:08 UTC, Meagain13 commented
Awesome!, thanks a lot for making time to solve my doubts.

Now I´ll keep translating more confidently, and will comment directly here if I have any other issue.

BTW!, I´ve also already signed the CLA, so just let me know if you need anything else.

Have a great weekend!

2021-01-16 15:32 UTC, Meagain13 commented
Hi Nick!

First of all, Happy 2021!

I´ve already signed the CLA last month, could you finally merge the translations I did last time?

And if you did it, could you tell me where I could see them?, I´ve just visited the page, but I saw that the sentences are still in English, and I´d like to see the changes before going on translating.

Cheers!

2021-02-23 11:26 UTC, Bryukh commented
Thanks!

2021-02-23 11:26 UTC, merged