Update zh-HANT.coco.coffee
codecombat/codecombat pull request #6631
Opened 2022-05-21 05:36 UTC by chengchiehhung

Translated some tags.

2022-05-21 20:19 UTC, nwinter requested changes
Thanks! Lost the initial character on `copyright_suffix` and `resource_hub`; can you add those back?

2022-05-21 20:19 UTC, nwinter commented on app/locale/zh-HANT.coco.coffee
> +    opyright_suffix: "保留所有權利"
```suggestion
    copyright_suffix: "保留所有權利"
```

2022-05-21 20:19 UTC, nwinter commented on app/locale/zh-HANT.coco.coffee
> +    esource_hub: "資源區域"
```suggestion
    resource_hub: "資源區域"
```

2022-05-22 06:13 UTC, chengchiehhung commented
Thanks for pointing out. Fixed it.

2022-06-03 22:56 UTC, nwinter approved these changes

2022-06-03 22:56 UTC, merged