fix
codecombat/codecombat pull request #6694
Opened 2022-07-08 03:10 UTC by smallst

this bug fix can work normally now. but maybe still lefts something

the bug is coming from: when we remove the leading string of a snippets . like we want to auto complete `hero.moveRight()` base on a line of `hero.moveRight(|)` when cursor is in the `|` , we would remove leading `hero.moveRight(` first. 
but we don't remove the left `)` in the line since we deal with trailing logic since the newLine is `)` instead of `hero.moveRight()` so if we remove the position from column 14 we remove nothing. 
so i add a condition to remove from column 0 

but i don't know if we have something snippets like `hero.moveTo(12)`, then if we remove `2` to update to `3` or if we remove the `1` and update to `2` if the regex works fine. since i don't understand clearly why we need removing trailing words.... can't imagine the situation. 

so let's wait more bug to fix if i introduce some bugs :joy:

2022-07-08 03:20 UTC, smallst commented
btw if you find you can understand why the fixed bug happens but cannot understand what i'm talking about in the final 2 sections. then that's right. You catch me.  i just don't know what other bugs may look like. i just have an idea about, maybe still some bugs left 😂

2022-07-13 16:15 UTC, nwinter requested changes
Fantastic! Not commenting on the code, but on the output behaviors here for Python only: I tested the original fix and looks good to me. Testing out the additional autocomplete cases, wonder if we can beef it up a bit?

If we are already autocompleting a hero property, limit it to those properties instead of pulling in all completion options. Here  `"attack"` should not be one of the options, because it's not a hero property:
<img width="759" alt="Screen Shot 2022-07-13 at 08 46 10" src="https://user-images.githubusercontent.com/99704/178777178-01061911-715b-44a6-bb22-193159d4c3fa.png">
<img width="610" alt="Screen Shot 2022-07-13 at 08 46 17" src="https://user-images.githubusercontent.com/99704/178777192-10e7f818-2951-4503-93e4-d6a50ac8c753.png">

Similarly, here `commandFriends` should not be one of the options:
<img width="683" alt="Screen Shot 2022-07-13 at 08 46 30" src="https://user-images.githubusercontent.com/99704/178777197-a7223707-3810-4629-b0a1-565b13bd5c35.png">

If I autocomplete a local variable that isn't a function, like this `highP` -> `highPriorityTypes`:
<img width="675" alt="Screen Shot 2022-07-13 at 08 46 56" src="https://user-images.githubusercontent.com/99704/178777201-7d733012-914b-4fb9-b473-e8d9ca74fea9.png">
...  it shouldn't add a newline after it when I press enter:
<img width="769" alt="Screen Shot 2022-07-13 at 08 47 00" src="https://user-images.githubusercontent.com/99704/178777205-671cc7cf-590c-4624-91d8-86547ab597e9.png">
Same for when I do that when it's not at the start of a line. Autocompleting player-defined functions can still have a newline if it's at the start of a line, but shouldn't if it's not (function being passed to another function, for example). This seems to be working ok for player-defined functions that do take arguments already.

We should also have any globals, like `'hero`, `pet`, `game`, etc. that are present also be in the autocomplete list, so that one can autcomplete `pe` -> `pet`, type `.`, and then be presented with just `pet.<whatever>` autocomplete options. The other options in this list are ok, just seems like `pet` itself should be the top choice:
<img width="783" alt="Screen Shot 2022-07-13 at 08 47 48" src="https://user-images.githubusercontent.com/99704/178777208-42b79487-a56f-413b-a43e-262dc4abdbb2.png">

While we do this, we should be careful we aren't introducing a needless `hero` autocomplete early in the game when it's better for us to just autocomplete all the top `hero.<whatever>` methods. For example, level 1 should still just have four autocomplete entries, not a fifth `hero` entry:
<img width="474" alt="Screen Shot 2022-07-13 at 08 57 36" src="https://user-images.githubusercontent.com/99704/178778992-d88db60a-6fdf-4d50-a186-5a97ba914692.png">

I'd like to be able to autocomplete within strings I've started, and to be able to autocomplete strings before I've started  typing anything, or when I've started typing the argument without quotes. We might need some game engine support to provide valid arguments to each method here? For example, here I'd like to have gotten a list of various valid `pet.on` event types before typing any argument characters, and for that to have gotten filtered down to ones that include `"sp"` (probably just `"spawn"`) after I type `"sp`, `"sp"`, or `sp`):
<img width="385" alt="Screen Shot 2022-07-13 at 08 48 19" src="https://user-images.githubusercontent.com/99704/178777215-05b93547-b619-49ff-bf2d-1564666a1c7a.png">

Similarly, I don't get any autocomplete on function arguments beyond the first one, would like to have functions provide info about their argument types so we can get smart about that:
<img width="693" alt="Screen Shot 2022-07-13 at 08 49 11" src="https://user-images.githubusercontent.com/99704/178777221-8082e5cb-8cd2-4495-96ad-8a0d386f9254.png">

Another example, where I don't get to autocomplete the `healerPosition` variable:
<img width="773" alt="Screen Shot 2022-07-13 at 08 49 43" src="https://user-images.githubusercontent.com/99704/178777222-6dd06d66-7815-4786-a4de-b841c76ed17d.png">

Can we get loop variables to autocomplete if they are in the loop? Here I would expect `friend` to be the top choice, but it'S not one of the options. In an ideal world, we would get all the scoping right to only present options that are in scope, but that sounds tricky?:
<img width="771" alt="Screen Shot 2022-07-13 at 08 48 49" src="https://user-images.githubusercontent.com/99704/178777218-e6633a47-819a-42cd-9e9f-d67d1cd8864c.png">

2022-07-14 03:30 UTC, smallst commented
- [x] If we are already autocompleting a hero property, limit it to those properties instead of pulling in all completion options. Here "attack" should not be one of the options, because it's not a hero property:

 - [x] If I autocomplete a local variable that isn't a function, like this highP -> highPriorityTypes:
... it shouldn't add a newline after it when I press enter:

 - [x] We should also have any globals, like 'hero, pet, game, etc. that are present also be in the autocomplete list, so that one can autcomplete pe -> pet, type ., and then be presented with just pet.<whatever> autocomplete options. The other options in this list are ok, just seems like pet itself should be the top choice:


 - [-] While we do this, we should be careful we aren't introducing a needless hero autocomplete early in the game when it's better for us to just autocomplete all the top hero.<whatever> methods. For example, level 1 should still just have four autocomplete entries, not a fifth hero entry:
Screen Shot 2022-07-13 at 08 57 36
    - we can't achieve this . but i think even we auto-complete the `hero` at level 1, the student can still typing `.` and get those 4 entries. yeah since we won't add newline here after `hero` . so not a big issue to add `hero` entry in level 1?

- [x] I'd like to be able to autocomplete within strings I've started, and to be able to autocomplete strings before I've started typing anything, or when I've started typing the argument without quotes. We might need some game engine support to provide valid arguments to each method here? For example, here I'd like to have gotten a list of various valid pet.on event types before typing any argument characters, and for that to have gotten filtered down to ones that include "sp" (probably just "spawn") after I type "sp, "sp", or sp):
    - have done with exists string in the code. didn't do about codecombat strings like `spawn` 

- [-] Similarly, I don't get any autocomplete on function arguments beyond the first one, would like to have functions provide info about their argument types so we can get smart about that:
    - oh we don't have arg types in js, python, .... maybe we could try in cpp/java ? 

 - [x] Another example, where I don't get to autocomplete the healerPosition variable:


- [-] Can we get loop variables to autocomplete if they are in the loop? Here I would expect friend to be the top choice, but it'S not one of the options. In an ideal world, we would get all the scoping right to only present options that are in scope, but that sounds tricky?:
    - for now i can't do good in this variables. since i'm using regex to find out possible variables. using `/[identifier] =/`. if we need the variables in `for [identifier] in` .. maybe i need to add a new regex. but i can. but, i don't have scope until now. and i'm creating new autocompletion on every 3 seconds (same with our auto save) so it can't be a syntax-based auto completion. so i only uses regex, that fast enough to do simple completion. just like how emacs CTAGS. but maybe i can make this regex-based completion much better using more complex logics.

2022-07-14 16:38 UTC, nwinter requested changes
> we can't achieve this . but i think even we auto-complete the hero at level 1, the student can still typing . and get those 4 entries. yeah since we won't add newline here after hero . so not a big issue to add hero entry in level 1?

It would still be better to make it simpler at the very beginning. If we were  able to add `hero` as its own entry, then maybe we don't do that unless there are more than 6 entries that also have `hero` in them?

>  have done with exists string in the code. didn't do about codecombat strings like `"spawn"`
I will discuss with game dev team on how we could provide the extra information to power this.

> oh we don't have arg types in js, python, .... maybe we could try in cpp/java ?
We sort of do, our LevelComponent docs that create the snippet entry in the first place have some data on what type all the arguments are. So we can read that while creating the snippet in the first place. However, it still doesn't know what the possible values are, dynamically for that level–game dev team can work on this perhaps.

The main point is that autocomplete doesn't work at all for the 2nd or 3rd arguments; it only works for the 1st.

> for now i can't do good in scope . since i'm using regex/tokenIdentifiers to find out possible variables. but, i don't have scope until now. and i'm creating new autocompletion on every 3 seconds (same with our auto save) so it can't be a syntax-based auto completion. so i only uses string, that fast enough to do simple completion. just like how emacs CTAGS.

This probably works fine without  getting into the complexity of doing this based on the AST for now, but we do [parse the code into an AST](https://github.com/codecombat/codecombat/blob/a8ea3ae3e7785b6f77e62e1e36798dfe9586faed/app/views/play/level/tome/SpellView.coffee#L863-L877) more often than that in the `aether_worker`, so we do have all that stuff available. Inserting the code change handler into `createOnCodeChangeMetaHandlers` [here](https://github.com/codecombat/codecombat/blob/a8ea3ae3e7785b6f77e62e1e36798dfe9586faed/app/views/play/level/tome/SpellView.coffee#L769-L792) or having it tag along with the `updateAether` function there is better than doing it on LevelSession save timing.

2022-07-14 16:38 UTC, nwinter commented on app/views/play/level/tome/editor/snippets.coffee
> +    unless /^(hero|self|this|@|db|game|ui)$/.test(fullPrefixParts[0]) or /^\s*$/.test(beginningOfLine) or /(,| |\()$/.test(beginningOfLine)
Should we get rid of old `self`, `this`, and `@`, now that it's been years since we have moved to `hero`, and add in `pet` here?

2022-07-14 16:38 UTC, nwinter commented on app/views/play/level/tome/SpellView.coffee
> +    console.log('debug: newid', newIdentifiers)
Don't need this log any more?

2022-07-14 16:38 UTC, nwinter commented on app/views/play/level/tome/SpellView.coffee
> +        unless next.value of newIdentifiers
And when I tried my Tabula Rasa code in C++, a similar error:

```
SpellView.coffee?4f9e:585 Uncaught TypeError: Cannot use 'in' operator to search for 'generator' in undefined
```

2022-07-15 03:45 UTC, smallst commented on app/views/play/level/tome/SpellView.coffee
> +    @addUserSnippets(e.spell.getSource(), e.spell.language, e.spell.view.ace.getSession())
oh strange. let me debug it

2022-07-15 07:10 UTC, smallst commented on app/views/play/level/tome/SpellView.coffee
> +        unless next.value of newIdentifiers
yeah stupid me .uses a variable `newIdentifiers` before it init 😂

2022-07-15 07:16 UTC, smallst commented on app/views/play/level/tome/SpellView.coffee
> +    @addUserSnippets(e.spell.getSource(), e.spell.language, e.spell.view.ace.getSession())
don't know why it happen. maybe the spell created before the spellView created ? let me add ?. in this call

2022-07-15 07:20 UTC, smallst commented
> The main point is that autocomplete doesn't work at all for the 2nd or 3rd arguments; it only works for the 1st.

this is solved now

and for hero, i add a condition that if hero doesn't show more than twice. since the first level only contains 1 hero.  and only need 3 hero. 
can't say we only enable hero when hero appears 6 times, most of levels don't have so many hero. 😂  otherwise we may just drop hero support . twice is fine for cs1 level1. & level 2. that's enough maybe.

2022-07-15 21:47 UTC, nwinter requested changes
Had time for a few more minutes of testing:
- [ ] `$.i18n.t` still erroring out in worker
- [ ] many cases where default hero method autocomplete is no longer working, like `hero.command` – no autocomplete options until I type the final `d`
- [ ] following function definitions give me autocomplete options for first and third function but now second function:
    ```python
    def newFunctionIJustMade():
        highPriorityTypes.append(["potion-master"])

    def functionWithThreeArgs(arg1, arg2, arg3):
        console.log(arg1, arg2, arg3)
    
    def newFunction2(a2, a3):
        console.log(a2, a3)
    ```
- [x] autocompleting a string that was found elsewhere in the code adds an extra trailing `"`, like `"he" -> `"heal""`
- [x] these standalone strings are showing up as autocomplete options for the first token on a line, but they shouldn't be there, don't usually want to start any statement with a string literal

By the way, I talked to game dev team to get some ideas of how we can get more dynamic parameter value enum data from the game engine to the front-end, and it seems doable, if not trivial, so at some point we may want to extend to use that, but probably not right now as part of this upgrade.

2022-08-17 00:48 UTC, merged