DT: Force skip levels
codecombat/codecombat pull request #6939
Opened 2023-03-20 14:15 UTC by adamkecskes

- new logic for level locking/skipping:
 Old logic: Marking one level from which all levels will be locked
 New logic: Each level can be marked as locked and/or optional individually

Marking logic: `locked` flag can be added with a date until which the lock will be effective.
 
 How we store the data?
 
 ```javascript
 classroom: {
   attributes: {
     studentLockMap: {
       lockedLevels: {
         [level1Original]: true // level1 is locked
         [level2Original]: Date // level2 is locked until Date
       },
       {
         optionalLevels: {
           [level1Original]: true // level1 is optional !! because level1 is also locked, this level will be shown as skipped (i.e. unaccessible) !! 
           [level3Original]: true // level3 is optional. It'll be accessible, student will be able to play it, but completion is not a prerequisite for accessing further levels 
         }
       }
     }
   }
 }
 ```
 -- Teacher view:
 On the Teacher Dashboard you'll be able to select multiple levels (in the table header) and students (left side of the table). 
 If you select them, two buttons will become active(shown):
  - Module Lock button - by clicking it each level in the module will be selected, and you'll be able to lock/skip/make-optional them 
  - Lock or Skip Levels button - by clicking it, you'll be able to lcok/skipt/optional the selected levels for the selected students
  
  -- Student view:
  Nothing much changed, the student's will be only able to play unskipped levels, and also will be able to choose if they'd like to play the optional ones.

2023-03-21 13:06 UTC, smallst commented
the overview looks good to me. i can test it by tomorrow.

2023-03-22 02:30 UTC, smallst requested changes
LGTM. left some comments but already push the fix.
BTW can we update such UI to say `skipped` instead of `locked`? 
![image](https://user-images.githubusercontent.com/11417632/226786583-3f6abd15-7522-49ba-adcf-ee73d24fc7be.png)

2023-03-22 02:30 UTC, smallst commented on app/views/play/CampaignView.coco.coffee
> +#      if level.slug == @courseInstance.get('startLockedLevel') # lock level begin from startLockedLevel
remove

2023-03-22 02:30 UTC, smallst commented on app/views/play/CampaignView.coco.coffee
> +      if this.courseInstance.get('lockedLevels').includes level.slug
`...get('lockedLevels')?.includes`

2023-03-22 02:30 UTC, smallst commented on ozaria/site/store/BaseSingleClass.js
> +          console.log('modifier', modifier, 'levelsToHandle', levelsToHandle)
remove

2023-03-22 02:30 UTC, smallst commented on app/templates/courses/teacher-class-view.pug
> +          - console.log(level.get('slug'), progress)
remove

2023-04-06 12:04 UTC, adamkecskes commented
@smallst UI now shows Skipped/Optional:
![levelstatus](https://user-images.githubusercontent.com/11805970/230373651-99e46f68-91ba-48dd-85e4-4699b49b12b9.gif)

2023-04-28 04:03 UTC, merged