/roblox page update
codecombat/codecombat pull request #7131
Opened 2023-10-08 14:52 UTC by adamkecskes

| BEFORE | AFTER | 
| --- | --- | 
| ![codecombat com_roblox (6)](https://github.com/codecombat/codecombat/assets/11805970/e6210fac-4289-4f52-9992-3ad813dacdb3) | ![localhost_3000_roblox (11)](https://github.com/codecombat/codecombat/assets/11805970/3aaf51bf-e137-42a7-adca-ed003487e2da) |

2023-10-08 16:40 UTC, nwinter requested changes
Apart from optimizing filesizes (landing page needs to be light), let's also tweak mobile responsiveness (Roblox is a big mobile focus):

## Header Image and Text
![IMG_0078](https://github.com/codecombat/codecombat/assets/99704/582114c6-4e2f-4a52-87ab-c20736ad0605)
Need another solution here on mobile. Maybe pull header text below the image? Or fade the image out when we know the text is going to be on top of the dark blue part instead of the sky? Or we could try another version of the asset where everything except the code editor part is faded significantly, we make the text light on dark instead of dark on light, and we prevent the text from overlapping the code editor part? Just ideas, have to play around with it.

## Account Linking Doesn't Fit
![IMG_0079](https://github.com/codecombat/codecombat/assets/99704/bd5f4ccd-9775-444c-a3c3-b1739205c926)
The way we do labels makes them extend outside this border. On mobile, we should also skip the two-column part with Roblox logo (skip the logo) and just have one column so that none of the lines wrap.

## Fish and Builder Character Assets Off-Screen
![IMG_0080](https://github.com/codecombat/codecombat/assets/99704/9ab004c4-35be-40ea-83c8-481c9796b8e3)
![IMG_0081](https://github.com/codecombat/codecombat/assets/99704/2cf8ed17-6504-4e44-a4b6-a0bff65ce7bf)
We could try to get them back on the screen, or just not show them.

2023-10-08 16:40 UTC, nwinter commented on app/assets/images/pages/roblox/Code_Combat_Thumbnail_wide.png
Let's try to get this filesize down. Dexecure will maybe load smaller versions of it automatically on smaller screens, but it won't load a narrower version that cuts off the extraneous sky/grass on the left that's just there for wide screens, we need to have separate cut versions for that.

Also, .webp and/or .jpg for it?

2023-10-08 16:40 UTC, nwinter commented on app/assets/images/pages/roblox/tree.png
Also pretty large for what it is. Crop some of the empty right transparency region, and also .webp when supported, and maybe smaller versions for smaller screens.

We can also just not show the tree at all when the screen gets small enough; we don't want it underlapping the text.

2023-10-09 09:37 UTC, adamkecskes commented
@nwinter thanks for all your comments, I've tried to make it responsive and also optimised the images:
| 500px | 600px | 800px | 990px | 1199px | 1600px | 
| --- | --- | --- | --- | --- | --- | 
| ![roblox_500](https://github.com/codecombat/codecombat/assets/11805970/64b52673-1ad9-4f72-bb6f-91ce06e13eb6) | ![roblox_600](https://github.com/codecombat/codecombat/assets/11805970/0e5fb461-f712-48f8-bf44-7ea614cc3d9f) | ![roblox_800](https://github.com/codecombat/codecombat/assets/11805970/b6a89987-7b54-49d7-b1dd-59553d1a8604) | ![roblox_990](https://github.com/codecombat/codecombat/assets/11805970/51c1e8d2-e9f2-483a-9775-e2e1bb33194c) | ![roblox_1199](https://github.com/codecombat/codecombat/assets/11805970/52a440d2-b8de-4e5b-9c72-76b6308a4355) | ![roblox_1600](https://github.com/codecombat/codecombat/assets/11805970/0ff8f103-dc71-44b3-a4ad-2e72fe343a40) |

2023-10-09 17:29 UTC, nwinter approved these changes
Nice! Responsiveness is very good now. We can merge this in now; it needs to be deployed by 7:30 am PDT on Tuesday at the latest, but can go earlier.

2023-10-09 17:29 UTC, nwinter commented on app/assets/images/pages/roblox/Code_Combat_Thumbnail_wide.png
I think we can delete this file now that we have the other versions of it.

2023-10-09 17:29 UTC, nwinter commented on app/assets/images/pages/roblox/header-bg/bg_full.png
I guess it probably won't matter because we should almost always show the .webp versions, but good god these .pngs are huge. Not necessarily worth converting now given how prevalent .webp is, but I would go .jpg on all the `bg_X` big headers that don't need transparency. (How did this one get to 5.28MB when the original Code_Combat_Thumbnail_wide.png was 1.41MB?)

2023-10-10 10:55 UTC, merged