ENG-306 - move new dashboard value from localStorage to user/aceConfig
codecombat/codecombat pull request #7294
Opened 2024-03-06 13:52 UTC by adamkecskes

2024-03-06 14:57 UTC, nwinter requested changes
This should go into some other config than `aceConfig`; `aceConfig` is for code-editor-related settings (Ace being the name of the code editor).

As to where to put it, I think a top-level user property is fine, maybe [here](https://github.com/codecombat/codecombat/blob/cf136d43a175a39511c50de5475a40b1ec521d2a/app/schemas/models/user.js#L404-L404) next to some other Boolean teacher dashboard properties.

As far as values go: `undefined` will currently mean "show old dashboard" and later will mean "show new dashboard", `false` will mean they've explicitly chosen to use the old dashboard, and `true` will mean they've explicitly chosen to use the new dashboard.

We _could_ also have it be, not boolean, but an enum string property, so that we could distinguish whether this is the first time we've shown them the new dashboard by default, so that we can show a first-time message highlighting what has changed and how to go back. Or we could store that extra temporary flag in local storage.

2024-03-07 05:29 UTC, mrfinch reviewed
could use `features` object in user for this too.

2024-03-07 09:01 UTC, adamkecskes commented
I've moved the flag into a separate property. (`features` didn't really work for me)
It is an enum now.

2024-03-11 04:52 UTC, mrfinch commented on app/schemas/models/user.js
> +  aceConfig: c.object({ default: { language: 'python', keyBindings: 'default', invisibles: false, indentGuides: false, behaviors: false, liveCompletion: true, newDashboard: false } }, {
remove

2024-03-11 04:52 UTC, mrfinch commented on app/schemas/models/user.js
> +  dashboardVersion: {
I dont think keeping it at top-level is a good idea. What issue did you face with features? Could create a new property `flags` if you need. We have properties like this: `seenNewDashboardModal`, `closedNewTDGetStartedTooltip` already which we should club into a single object(later work)

2024-03-11 04:52 UTC, mrfinch commented on app/schemas/models/user.js
> +    enum: ['default', 'old-coco', 'merged'],
why do we need default? Won't null be treated as default?

2024-03-14 07:47 UTC, adamkecskes commented
@mrfinch I'm not really sure what was my issue with features last time, but now it works...
Backend PR: https://github.com/codecombat/codecombat-server/pull/834

2024-03-14 08:15 UTC, mrfinch commented on app/schemas/models/user.js
> +  aceConfig: c.object({ default: { language: 'python', keyBindings: 'default', invisibles: false, indentGuides: false, behaviors: false, liveCompletion: true, newDashboard: false } }, {
you missed this?

2024-03-14 11:37 UTC, mrfinch commented on app/models/User.js
> +      return me.get('features')?.isNewDashboardActive
this.get('features')?.isNewDashboardActive

2024-03-14 11:40 UTC, mrfinch approved these changes

2024-03-15 10:51 UTC, merged