ENG-244 - new header/footer
codecombat/codecombat pull request #7308
Opened 2024-03-13 09:00 UTC by adamkecskes

<img width="1077" alt="Cursor_and_CodeCombat_-_Coding_games_to_learn_Python_and_JavaScript___CodeCombat" src="https://github.com/codecombat/codecombat/assets/11805970/db092a8d-a09d-43d1-a06f-a1ffbece1ea7">

<img width="1072" alt="CodeCombat_-_Coding_games_to_learn_Python_and_JavaScript___CodeCombat" src="https://github.com/codecombat/codecombat/assets/11805970/5db0ba77-a789-4810-8be8-1e824ae1e017">

2024-03-13 15:08 UTC, nwinter requested changes
I talked to Brehan about the flags for language selection thing. His intention was to save space and clean up the design, but [UX best practices suggest against](https://www.google.com/search?q=web+design+use+flags+for+language+selection) (flags are not even close to 1:1 with languages, other issues). So, let's actually take the country flags back out.

What we can do to save space is just show "English" instead of "English (US)", or "español" instead of "español (América Latina)", when we are not in the full dropdown, so that the wider languages don't take up as much space.

I haven't tested on mobile, with a long language that needs more space for the nav entries, with various account types, but let's make sure to do that, especially on the /ai page where we were adding the AI HackStack logo to the top nav, to make sure everything fits.

By the way, I also discussed with Brehan, we are going to make further changes to the navigation links in the header as we figure out how to include more of our products there, but don't need to block on that.

2024-04-18 12:17 UTC, mrfinch reviewed
- Individual account navbar is broken
<img width="995" alt="Screenshot 2024-04-18 at 5 42 43 PM" src="https://github.com/codecombat/codecombat/assets/6376157/ff4fc667-4e9d-402c-9d30-dd4f7db38793">

- Same issue with student account too. 
- Also, spacing between 'my account' and flag is huge after we log-in.
- Do we need to show premium, self-paced options for student? We need to confirm it

2024-04-22 10:40 UTC, mrfinch commented on app/components/common/Navigation.vue
> +  TEACHER_TOOLKIT_PREVIEW: { url: '/teachers/resources', title: 'nav.teacher_toolkit_preview' },
I haven't been able to replicate it. We can skip my comment for now.

2024-04-22 10:43 UTC, mrfinch approved these changes
LGTM now. I have asked Brehan for Home user in the document.

Can we push this to next for for more testing?

2024-04-23 19:59 UTC, nwinter approved these changes
Added some suggestions for style tweaks I noticed on reading the code, but generally looks good.

2024-04-23 19:59 UTC, nwinter commented on package.json
> +    "language-flag-colors": "^3.1.0",
We can get rid of this package

2024-04-23 19:59 UTC, nwinter commented on app/views/core/RootView.coffee
> +
```suggestion
```

2024-04-23 19:59 UTC, nwinter commented on package.json
> +    "language-flag-colors": "^3.1.0",
```suggestion
```

2024-04-23 19:59 UTC, nwinter commented on package-lock.json
> +        "language-flag-colors": "^3.1.0",
```suggestion
```

2024-04-23 19:59 UTC, nwinter commented on package-lock.json
> +    },
```suggestion
```

2024-04-23 19:59 UTC, nwinter commented on package-lock.json
> +    },
```suggestion
```

2024-04-23 19:59 UTC, nwinter commented on app/locale/en.js
> +      ai_hackstack_junior_beta: 'AI HackStack Junior (Beta)',
We decided to cal this AI Junior instead of AI HackStack Junior.

```suggestion
      ai_junior_beta: 'AI Junior (Beta)',
```

2024-04-23 19:59 UTC, nwinter commented on app/components/common/Footer.vue
> +            items.AI_HACKSTACK_JUNIOR,
```suggestion
            items.AI_JUNIOR,
```

2024-04-23 19:59 UTC, nwinter commented on app/components/common/Navigation.vue
> +  AI_HACKSTACK_JUNIOR: { url: 'https://docs.google.com/forms/d/e/1FAIpQLSfcWo6JVeFP30OslksUwE1Z-XyWFIKW3h81v08aYU1-vbhSUA/viewform', attrs: { target: '_blank' }, title: 'nav.ai_hackstack_junior_beta'
```suggestion
  AI_JUNIOR: { url: 'https://docs.google.com/forms/d/e/1FAIpQLSfcWo6JVeFP30OslksUwE1Z-XyWFIKW3h81v08aYU1-vbhSUA/viewform', attrs: { target: '_blank' }, title: 'nav.ai_junior_beta' },
```

2024-04-23 19:59 UTC, nwinter commented on app/components/common/Navigation.vue
> +              description: 'nav.ai_hackstack_junior_description'
```suggestion
              ...items.AI_JUNIOR,
              description: 'nav.ai_junior_description'
```

2024-04-23 19:59 UTC, nwinter commented on app/components/common/Navigation.vue
> +            items.AI_HACKSTACK_JUNIOR
```suggestion
            items.AI_JUNIOR
```

2024-04-23 19:59 UTC, nwinter commented on app/components/common/Navigation.vue
> +            items.AI_HACKSTACK_JUNIOR,
```suggestion
            items.AI_JUNIOR,
```

2024-04-23 19:59 UTC, nwinter commented on app/components/common/Navigation.vue
> +            items.AI_HACKSTACK
```suggestion
            items.AI_JUNIOR
```

2024-04-23 19:59 UTC, nwinter commented on app/locale/en.js
> +      ai_hackstack_junior_description: 'Introduces multimodal generative AI in a simple and intuitive platform designed specifically for K-5 students.',
```suggestion
      ai_junior_description: 'Introduces multimodal generative AI in a simple and intuitive platform designed specifically for K-5 students.',
```

2024-04-23 19:59 UTC, nwinter commented on app/components/common/FinalFooter.vue
> +    .copyright
Are these social links showing when it's in China mode? Might need to check that they aren't.

2024-04-23 19:59 UTC, nwinter commented on app/views/core/RootView.coffee
> +      @$el.find('.language-dropdown-current')?.html("<span class=\"emoji-flag\">#{emoji}</span>")
```suggestion
    if newLang isnt 'en-US'
      @$el.find('.language-dropdown-current')?.text(locale[newLang].nativeDescription)
    else
      @$el.find('.language-dropdown-current')?.html("<span class=\"emoji-flag\">🇺🇸</span>")
```

2024-04-26 06:51 UTC, merged