Coco JR marketing page
codecombat/codecombat pull request #7716
Opened 2024-09-19 06:01 UTC by adamkecskes

| desktop | mobile | 
| --- | --- | 
| ![localhost_3000_junior](https://github.com/user-attachments/assets/b9320c8e-9af1-489c-97ea-0c248ae80291) | ![localhost_3000_junior (1)](https://github.com/user-attachments/assets/3b805ba2-3cb7-4f80-906b-ed7f734ae369) |

2024-09-19 16:47 UTC, nwinter requested changes
Visually, the page looks great! Found a bunch of minor stuff.

The blue bolded "CodeCombat Junior" elements throughout the page look like links but aren't links. I guess this is the same issue as in these elements on the /schools page, but those aren't as prominent (they don't start until the AI HackStack section). Maybe here, and there, we can adjust the design slightly to avoid collision with links?

_Can you tell which of these are links?_
<img width="1168" alt="Screenshot 2024-09-19 at 08 43 29" src="https://github.com/user-attachments/assets/51245a64-3282-42a9-b9b0-ce069189af7b">
<img width="513" alt="Screenshot 2024-09-19 at 08 48 53" src="https://github.com/user-attachments/assets/938463b4-ad72-48b0-94f3-32be238c98c7">
<img width="652" alt="Screenshot 2024-09-19 at 08 49 02" src="https://github.com/user-attachments/assets/21d81514-d7c0-42c8-b72e-37d462876cbc">
<img width="505" alt="Screenshot 2024-09-19 at 08 49 09" src="https://github.com/user-attachments/assets/e1bd1cde-92e8-457d-92c9-af2efdc71b36">
<img width="1245" alt="Screenshot 2024-09-19 at 08 49 17" src="https://github.com/user-attachments/assets/f477c4b4-33dd-4bf1-ae8d-35e1c5b6f670">
<img width="691" alt="Screenshot 2024-09-19 at 08 49 26" src="https://github.com/user-attachments/assets/0edd32f3-78db-42d2-8528-60215c4648b2">

Mobile version has a bunch of dead white space at the top of the page. (This is also true of other landing pages.) Is this intentional? I would think we would pull all lthat up, or at least put a cool logo there or something.
![CodeCombat the most effective computer science solution for schools](https://github.com/user-attachments/assets/8ece7bc2-3fb3-4400-9c82-67c389ac8c1a)

Lighthouse on marketing pages is important; checked it for desktop real quick, looks ok, although there are a few things to fix. You can run it yourself to see their list. Doesn't need to be perfect, but check for low-hanging fruit.
<img width="425" alt="Screenshot 2024-09-19 at 09 43 19" src="https://github.com/user-attachments/assets/2a07df4b-0671-4de8-b8b3-640967711127">
I think the biggest question from this is what to do about the Cloudflare video at the top, which loads a bunch of data. If it impacts Lighthouse scores, is there a good way to defer it such that it doesn't?

For all fixes, consider doing them on all the other pages built out of similar components or methods.

2024-09-19 16:47 UTC, nwinter commented on app/locale/en.js
> +      testimonials_1_quote: 'The future is programmable and you will need to be able to code to participate…I think CoCo [CodeCombat] has the best CS curriculum on the market… the teacher tool kit is
We can fix up the formatting a bit here.
```suggestion
      testimonials_1_quote: 'The future is programmable and you will need to be able to code to participate… I think CodeCombat has the best CS curriculum on the market… the teacher toolkit is what sets it apart.',
```

2024-09-19 16:47 UTC, nwinter commented on app/locale/en.js
> +      no_matter_the_coding_experience: 'No matter the coding experience, **CodeCombat Junior** meets students where they’re at. They can code with icon blocks, word blocks, blocks and text code in pa
```suggestion
      no_matter_the_coding_experience: 'No matter the coding experience, **CodeCombat Junior** meets students where they’re at. They can program with icon blocks, word blocks, blocks and text code in parallel, or text-based code with industry-standard languages like Python and JavaScript.',
```

2024-09-19 16:47 UTC, nwinter commented on app/locale/en.js
> +      faq_4_answer: 'FAQ 4 Answer',
This content is coming, right?

2024-09-19 16:47 UTC, nwinter commented on app/locale/en.js
> +      meta_title: 'Meta Title',
```suggestion
      meta_title: 'CodeCombat Junior: K-5 Computer Science for Schools',
```

2024-09-26 18:04 UTC, mrfinch approved these changes

2024-09-26 18:06 UTC, merged